### ISSUE TITLE
Support sharing binary

### ISSUE THREAD

**Issue by noir-neo** [noir-neo/UnityARKitMultipeerConnectivity#21]
to serialize in c# layer

**Comment by andrewnakas** [comment]
Nice, I was trying to add  a data object to your code that held a byte stream, but failed casting the objects in objective c/ swift.  if you add this in I'll publish an open source arkit fps starter project forked from this amazing implementation of local multiplayer connectivity. Thanks!

**Comment by noir-neo** [comment]
I merged this resolution. any feedback is welcome!
