### ISSUE TITLE
Add a sample of collaborative session

### ISSUE THREAD

**Issue by noir-neo** [noir-neo/UnityARKitMultipeerConnectivity#25]
this dependents on #24 

https://blogs.unity3d.com/jp/2019/06/06/ar-foundation-support-for-arkit-3/

**Comment by crocoking** [comment]
It's a good idea! Do you have a date when to do it?

**Comment by noir-neo** [comment]
ok, I'll do it sometime soon.

**Comment by crocoking** [comment]
> ok, I'll do it sometime soon.

I am doing it. But I face many problems. Waiting for your demo.

**Comment by noir-neo** [comment]
Hi @crocoking, I did it in #32. I want you to try it!

**Comment by crocoking** [comment]
> Hi @crocoking, I did it in #32. I want you to try it!

I have updated you code #32. My question is that ARCollaborationData is a continuous send and receive process different from ARWorldMap which send just once.
