### ISSUE TITLE
Send byte[] from swift to c#

### ISSUE THREAD

**Issue by crocoking** [noir-neo/UnityARKitMultipeerConnectivity#33]
Hi, noir-neo, You demo is good. But I have some question about how to send byte[] form swift to c#. Your swift code is this:
`        data.withUnsafeBytes { (ptr: UnsafePointer<UInt8>) in
            let rawPtr = UnsafeMutableRawPointer(mutating: ptr)
            DispatchQueue.main.async {
                self.dataReceived(rawPtr, CInt(data.count))
            }
        }`
Can you explain it? As I am using objective-c, I don't know how to write with objective-c. thank you.

**Comment by noir-neo** [comment]
See this line https://github.com/noir-neo/UnityARKitMultipeerConnectivity/blob/master/Assets/UnityMultipeerConnectivity/Plugins/iOS/NativeInterface/UnityMCSessionNativeInterface.cs#L65
